args <- commandArgs(trailingOnly=T)
print(" ++ Setting new wd")
setwd(args[1])
print(" ++ Reading combined data")
data = read.table(args[2], header=T, sep="\t")
graph_name = args[3]
cex_paper = 1.5

print(" ++ Plotting acs")
pdf(paste(graph_name, "_acs.pdf", sep=""))
min_y = min(data$a_cs)
max_y = max(data$a_cs)
plot(data$a_cs, type="l", col="#000000", xlab=expression(tau ~ " (in months)"), ylab=expression("a"[c]), cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y))
title("Critical Activity Evolution", cex.main=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting ratios and k1s")
pdf(paste(graph_name, "_ratios.pdf", sep=""))
min_y = min(min(data$ratios), min(data$k1s))
max_y = max(max(data$ratios), max(data$k1s))
colors = c("#000000", "#858585")
plot(data$ratios, type="l", col=colors[1], xlab=expression(tau ~ " (in months)"), ylab="ratio", cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y))
lines(data$k1s, col=colors[2], lty=2)
title(expression("Ratio " ~ (frac(lambda,mu)) ~ " over " ~ tau ~ " (in months)"))
legend("bottomright", pch=c(1,NA), col=colors, legend=c("Ratio", expression(kappa[1])), lty=c(1,2), cex=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting gs")
pdf(paste(graph_name, "_gs.pdf", sep=""))
min_y = min(data$gs)
max_y = max(data$gs)
plot(data$gs, type="l", col="#000000", xlab=expression(tau ~ " (in months)"), ylab=expression("g(a"[j] ~ ")"), cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y))
title(expression("g(a"[j] ~ ")"), cex.main=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting max_qs")
pdf(paste(graph_name, "_max_qs.pdf", sep=""))
min_y = min(data$max_qs)
max_y = max(data$max_qs)
plot(data$max_qs, type="l", col="#000000", xlab=expression(tau ~ " (in months)"), ylab="q", cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y))
title("Maximal Peer Activity Flow Evolution", cex.main=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting mus")
pdf(paste(graph_name, "_mus.pdf", sep=""))
min_y = min(data$mus)
max_y = max(data$mus)
plot(data$mus, type="l", col="#000000", xlab=expression(tau ~ " (in months)"), ylab=expression(mu), cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y))
title(expression("Evolution of " ~ mu), cex.main=cex_paper)
grid(col="gray", lwd=1)
dev.off()
