args <- commandArgs(trailingOnly=T)
print(" ++ Setting new wd")
setwd(args[1])
print(" ++ Reading combined data")
data = read.table(args[2], header=T, sep="\t")
sim_act_x = read.table(args[4], header=F)
sim_act_y = read.table(args[3], header=F)
graph_name = args[5]
cex_paper = 1.5
cex_size = 0.6

print(" ++ Plotting acs")
pdf(paste(graph_name, "_acs.pdf", sep=""))
min_y = min(data$a_cs)
max_y = max(data$a_cs)
plot(data$a_cs, type="b", col="#000000", xlab="Months", ylab=expression("a"[c]), cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y), pch=1)
title("Critical Activity Evolution", cex.main=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting ratios and k1s")
pdf(paste(graph_name, "_ratios.pdf", sep=""))
min_y = min(min(data$ratios), min(data$k1s))
max_y = max(max(data$ratios), max(data$k1s))
colors = c("#000000", "#858585")
plot(data$ratios, type="b", col=colors[1], xlab="Months", ylab="ratio", cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y), pch=1)
lines(data$k1s, col=colors[2], lty=2)
title(expression("Ratio " ~ (frac(lambda,mu)) ~ " over " ~ tau ~ " (in months)"))
legend("bottomright", pch=c(1,NA), col=colors, legend=c("Ratio", expression(kappa[1])), lty=c(1,2), cex=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting gs")
pdf(paste(graph_name, "_gs.pdf", sep=""))
min_y = min(data$gs)
max_y = max(data$gs)
plot(data$gs, type="b", col="#000000", xlab="Months", ylab=expression("g(a"[j] ~ ")"), cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y), pch=1)
title(expression("g(a"[j] ~ ")"), cex.main=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting max_qs")
pdf(paste(graph_name, "_max_qs.pdf", sep=""))
min_y = min(data$max_qs)
max_y = max(data$max_qs)
plot(data$max_qs, type="b", col="#000000", xlab="Months", ylab="q", cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y), pch=1)
title("Maximal Peer Activity Flow Evolution", cex.main=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting mus")
pdf(paste(graph_name, "_mus.pdf", sep=""))
min_y = min(data$mus)
max_y = max(data$mus)
plot(data$mus, type="b", col="#000000", xlab="Months", ylab=expression(mu), cex.axis=cex_paper, cex.lab=cex_paper, ylim=c(min_y, max_y), pch=1)
title(expression("Evolution of " ~ mu), cex.main=cex_paper)
grid(col="gray", lwd=1)
dev.off()

print(" ++ Plotting activity")
pdf(paste(graph_name, "_activity.pdf", sep=""))
par(mar=c(5,5,4,5)+.1)
plot(sim_act_x[,1], sim_act_y[,1], type="l", pch=4,xlab=expression(tau ~ " (in months)"), 
     ylab=expression("Simulated Activity over " ~ a[c]), lty=2,
     col="#000000", cex=cex_size, cex.axis=cex_paper, cex.lab=cex_paper)#, ylim=c(y_min, y_max))
title(substitute(atop("Activity over " ~ tau ~ " (in months)", 
                      Delta ~ tau == ~ dt ~ ", " ~ mu == ~ dp ~ ", " ~ a[c] == ~ ac),
                 list(dt = 0.001, dp = 0, ac = 0)), cex.main=cex_paper)
grid(col="gray", lwd=1)
par(new=TRUE)
plot(data$real_act_x, data$real_act_y, type="o", lty=1, pch=2,xaxt="n",yaxt="n",xlab="",ylab="", 
     col="#858585", cex=cex_size, cex.axis=cex_paper, cex.lab=cex_paper)
axis(4, cex.axis=cex_paper)
mtext("Real Activity",side=4,line=3, cex=cex_paper)
legend("topleft", pch=c(NA,2), col=c("#000000", "#858585"), legend=c("Simulated Activity", "Observed Activity"), lty=c(2,1), cex=cex_paper)
dev.off()
